services:
    _defaults:
            autowire: true
            autoconfigure: true

    Morgenbord\ChecklistWidgetBundle\:
        resource: '../src/'
    
    # Declare event listeners that declare widgets
    register_checklist_widget.listener:
        class: Morgenbord\ChecklistWidgetBundle\ChecklistWidgetParameters
        tags:
            - { name: kernel.event_listener, event: morning_bord.register_widget }
